REVOKE ALL ON SCHEMA api FROM PUBLIC;
REVOKE ALL ON SCHEMA api FROM deployer;
REVOKE ALL ON SCHEMA api FROM postgres;

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;

GRANT ALL ON SCHEMA api TO postgres;
GRANT ALL ON SCHEMA api TO deployer;
GRANT ALL ON SCHEMA api TO PUBLIC;
GRANT ALL ON SCHEMA public TO deployer;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO PUBLIC;

GRANT ALL ON ALL TABLES IN SCHEMA api TO postgres;
GRANT ALL ON ALL TABLES IN SCHEMA api TO deployer;
GRANT ALL ON ALL TABLES IN SCHEMA api TO PUBLIC;
GRANT ALL ON ALL TABLES IN SCHEMA public TO deployer;
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres;
GRANT ALL ON ALL TABLES IN SCHEMA public TO PUBLIC;

GRANT ALL ON SCHEMA api TO GROUP unregistered;
GRANT ALL ON SCHEMA api TO GROUP registered;
GRANT ALL ON ALL TABLES IN SCHEMA api TO GROUP unregistered;
GRANT ALL ON ALL TABLES IN SCHEMA api TO GROUP registered;

--
-- PostgreSQL database dump complete
--
